//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Critter
	{
		private string name;
		private int wounds;
		private int currentWounds;
		private bool dead;
		private int[] stats;


		public Critter ()
		{



		}


		
		public string GetName ()
		{
			return name;
		}
		
		
		public int GetStats (int which_stat)
		{
			return stats [which_stat];
		}
		
		public int[] GetStats ()
		{
			return stats;
		}
		
		
		public int GetWounds ()
		{
			return currentWounds;
		}
		
		public int AddDamage (int damage)
		{
			this.currentWounds = this.currentWounds - damage;
			if (this.currentWounds <= 0)
				this.dead = true;
			return this.wounds;
		}
		
		public int HealDamage (int healed)
		{
			if (this.currentWounds + healed > this.wounds) {
				this.currentWounds = this.wounds;
			} else {
				this.currentWounds = this.currentWounds + healed;
			}
			return this.currentWounds;
		}

	}
}

