//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Storymaattori
{
	public class TextGenerator
	{
		private string fileLocation;

		public TextGenerator (string fileLocation)
		{
			this.fileLocation = fileLocation;
		}

		public string GenerateCallsign()
		{
			return "boo";
		}

		public string GenerateSoldierName()
		{
			return "Esi M. Erkki";
		}

		public string GenerateSociety()
		{
			return "empire of slavic elves";
		}

		public string GenerateMonsterName()
		{
			return "snotling";
		}

	}
}

